<?php
/**
 * Implements hook_permission().
 */
function ya_donate_permission() {
  return array(
    'access yamoney donate settings' => array(
      'title' => t('Access Yandex.Money donate settings'),
      'description' => t('Yandex money donate settings.'),
    ),
    'view donate block' => array(
      'title' => t('Access Yandex.Money donate block'),
      'description' => t('Yandex.Money donate block.'),      
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ya_donate_menu() {
  $items['admin/config/services/yamoney/donate'] = array(
    'title' => 'Settings of Yandex.Money donate module',
    'description' => 'Yandex money danate settings page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ya_donate_settings'),
    'access arguments' => array('access yamoney donate settings'),
    'weight' => 3,
  );
  return $items;
}

function ya_donate_settings(){
  $form = array();
  $form['yamoney_donate_receiver'] = array(
    '#type' => 'textfield',
    '#title' => t('Purse number'),
    '#default_value' => variable_get('yamoney_donate_receiver', ''),
  );
  $form['ya_donate_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Donate text'),
    '#default_value' => variable_get('ya_donate_text', ''),
  );
  $form['ya_donate_text_targets'] = array(
    '#type' => 'textfield',
    '#title' => t('Details of payment'),
    '#default_value' => variable_get('ya_donate_text_targets', ''),
  );
  $form['ya_donate_button_text'] = array(
    '#type' => 'textfield',
    '#title' => t('The text on the button'),
    '#description' => t('If empty then default value will be').': '.t('Donate'),
    '#default_value' => variable_get('ya_donate_button_text', ''),
  );
  $form['ya_donate_user_amount'] = array(
    '#type' => 'textfield',
    '#title' => t('Default donate amount'),
    '#default_value' => variable_get('ya_donate_user_amount', ''),    
  );
  return system_settings_form($form);
}

function ya_donate_settings_validate($form, &$form_state){
  if(!is_numeric($form_state['values']['ya_donate_user_amount']) && !empty($form_state['values']['ya_donate_user_amount'])) {
    form_set_error('ya_donate_user_amount', t('This field is not numeric!!!'));
  }
}

/**
 * Implements hook_block_info().
 */
function ya_donate_block_info(){
  $blocks['donate_block'] = array(
    'info' => t('Yandex.Money donate block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ya_donate_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'donate_block':
      if (user_access('view donate block')) {
        $block['content'] = drupal_get_form('ya_donate_block_form');
      }
      break;
  }
  return $block;
}

function ya_donate_block_form(){
  $form = array();
  if(empty(variable_get('yamoney_donate_receiver', ''))) {
    $form['empty'] = array(
      '#markup' => t('Unknown payment recipient'),
    );
    return $form;
  }
  $button = variable_get('ya_donate_button_text', '');
  if(empty($button)){
    $button = t('Donate');
  }
  $form['text'] = array(
    '#type' => 'item',
    '#title' => variable_get('ya_donate_text', ''),
  );
  $form['sum'] = array(
    '#type' => 'textfield',
    '#title' => t('Donate amount'),
    '#description' => t('Enter the amount of the donation'),
    '#default_value' => variable_get('ya_donate_user_amount', ''),
  );
  $form['receiver'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('yamoney_donate_receiver'),
  );
  $form['quickpay-form'] = array(
    '#type' => 'hidden',
    '#value' => 'donate',
  );
  $form['formcomment'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('ya_donate_text_targets', ''),
  );
  $form['short-dest'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('ya_donate_text_targets', ''),
  );
  $form['targets'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('ya_donate_text_targets', ''),
  );
  $form['need-email'] = array(
    '#type' => 'hidden',
    '#value' => 'true'
  );
  $form['payment-type'] = array(
    '#type' => 'hidden',
    '#value' => 'PC',
  );    
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => $button,
  );
  $form['#action'] = 'https://money.yandex.ru/quickpay/confirm.xml';
  return $form;
}
